name: freed_pt
channels:
  - rdkit
  - pytorch
  - dglteam
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.14.5
  - cudatoolkit=10.2.89
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.7.1
  - dgl-cuda10.1=0.5.3
  - dgl-cuda10.2=0.5.3
  - entrypoints=0.3
  - expat=2.2.10
  - fontconfig=2.13.1
  - freetype=2.10.4
  - glib=2.66.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib_metadata=3.7.3
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jinja2=2.11.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.3.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libboost=1.73.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.40.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.1
  - mistune=0.8.4
  - mkl=2020.2=256
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mpi=1.0=mpich
  - mpi4py=3.0.3
  - mpich=3.3.2
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.5
  - ninja=1.10.2
  - notebook=6.2.0
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openbabel=3.1.1
  - openssl=1.1.1h
  - pandas=1.2.1
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.8.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.3.3
  - pixman=0.38.0
  - prometheus_client=0.9.0
  - prompt_toolkit=3.0.8=0
  - ptyprocess=0.7.0
  - py-boost=1.73.0
  - pycparser=2.20
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7=1_cp37m
  - pytorch=1.7.1
  - pytz=2020.5
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - rdkit=2020.09.1.0
  - readline=8.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=51.3.3
  - sip=4.19.24
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.9.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - torchvision=0.8.2
  - tornado=6.0.4
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.11.0
    - cachetools==4.2.0
    - chardet==4.0.0
    - cloudpickle==1.2.1
    - crem==0.2.5
    - cycler==0.10.0
    - future==0.18.2
    - gdown==3.13.0
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.35.0
    - gym==0.18.0
    - idna==2.10
    - importlib-metadata==3.4.0
    - iniconfig==1.1.1
    - ipython==7.19.0
    - jedi==0.18.0
    - joblib==1.0.0
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - matplotlib==3.1.1
    - oauthlib==3.1.0
    - packaging==20.8
    - pillow==7.2.0
    - pluggy==0.13.1
    - prompt-toolkit==3.0.11
    - protobuf==3.14.0
    - psutil==5.8.0
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.0
    - pygments==2.7.4
    - pytest==6.2.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.1
    - toml==0.10.2
    - tqdm==4.56.0
    - urllib3==1.26.2
    - werkzeug==1.0.1
    - zipp==3.4.0
